# Generated by Django 3.2.6 on 2021-08-09 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, validators=[shop.products.validators.is_alpha_or_space_validator])),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='products')),
                ('description', models.TextField()),
                ('is_sold', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
