# Generated by Django 3.2.6 on 2021-08-09 10:30

from django.db import migrations, models
import django.db.models.deletion
import shop.profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=30, validators=[shop.profiles.validators.only_letters_validator])),
                ('phone_number', models.CharField(blank=True, max_length=30, validators=[shop.profiles.validators.only_digits_validator])),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop_auth.shopuser')),
            ],
        ),
    ]
